/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazRGI;

import Mundo.conectar;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jucaszuse
 */
public class InterfazLogin extends javax.swing.JFrame {

    ArrayList listaDia;
    ArrayList listaAños;

    /**
     * Creates new form InterfazLogin
     */
    public InterfazLogin() {
        initComponents();
        listaDia = new ArrayList();
        listaAños = new ArrayList();
        setLocationRelativeTo(this);
        this.setAlwaysOnTop(true);
        cargarListaDeDia();
        cargarListaDeAño();
        bloquear();
        llenarCombo();
        llenarComboPais();
        setTitle("REGISTRO");
    }

    void bloquear() {
        txtSegundoNombre.setEnabled(false);
    }

    private void cargarListaDeDia() {
        for (int i = 1; i <= 30; i++) {
            cbDia.addItem(i);
        }
    }

    private void cargarListaDeAño() {
        for (int i = 1940; i <= 2012; i++) {
            cbAño.addItem(i);
        }
    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbPais = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cbDia = new javax.swing.JComboBox();
        cbMes = new javax.swing.JComboBox();
        cbAño = new javax.swing.JComboBox();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        txtRepitaContraseña = new javax.swing.JPasswordField();
        txtSegundoApellido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSegundoNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rSi = new javax.swing.JRadioButton();
        rNo = new javax.swing.JRadioButton();
        rS = new javax.swing.JRadioButton();
        rN = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcMousePanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jcMousePanel1.setForeground(new java.awt.Color(255, 255, 255));
        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo nuevo registro.png"))); // NOI18N
        jcMousePanel1.setIconLogo(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRIMER NOMBRE");
        jLabel1.setBounds(30, 20, 130, 15);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtNombre.setBackground(new java.awt.Color(255, 0, 0));
        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        txtNombre.setBounds(220, 10, 170, 30);
        jLayeredPane1.add(txtNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRIMER APELLIDO");
        jLabel2.setBounds(30, 90, 150, 30);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtApellido.setBackground(new java.awt.Color(255, 0, 0));
        txtApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoKeyReleased(evt);
            }
        });
        txtApellido.setBounds(220, 90, 170, 30);
        jLayeredPane1.add(txtApellido, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PAIS");
        jLabel3.setBounds(30, 190, 70, 30);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cbPais.setBackground(new java.awt.Color(51, 153, 255));
        cbPais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbPais.setBounds(230, 190, 140, 30);
        jLayeredPane1.add(cbPais, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SEXO");
        jLabel4.setBounds(30, 260, 50, 30);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jRadioButton1.setBackground(new java.awt.Color(0, 153, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("HOMBRE");
        jRadioButton1.setBounds(230, 260, 90, 30);
        jLayeredPane1.add(jRadioButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jRadioButton2.setBackground(new java.awt.Color(51, 153, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("MUJER");
        jRadioButton2.setBounds(370, 260, 90, 30);
        jLayeredPane1.add(jRadioButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FECHA DE NACIMINENTO");
        jLabel5.setBounds(20, 330, 160, 30);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cbDia.setBackground(new java.awt.Color(0, 153, 255));
        cbDia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbDia.setBounds(230, 330, 70, 30);
        jLayeredPane1.add(cbDia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cbMes.setBackground(new java.awt.Color(51, 153, 255));
        cbMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbMes.setBounds(330, 330, 130, 30);
        jLayeredPane1.add(cbMes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cbAño.setBackground(new java.awt.Color(51, 153, 255));
        cbAño.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbAño.setBounds(480, 330, 120, 30);
        jLayeredPane1.add(cbAño, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtNombreUsuario.setBackground(new java.awt.Color(255, 0, 0));
        txtNombreUsuario.setEditable(false);
        txtNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombreUsuario.setBounds(230, 390, 180, 30);
        jLayeredPane1.add(txtNombreUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONTRASEÑA");
        jLabel7.setBounds(30, 430, 130, 20);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("REPITA CONTRASEÑA");
        jLabel8.setBounds(30, 470, 160, 20);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Approve-48.png"))); // NOI18N
        jButton1.setText("CONFIRMAR REGISTRO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(30, 540, 230, 60);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back Button_32.png"))); // NOI18N
        jButton2.setText("VOLVER AL INICIO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(400, 540, 240, 60);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtContraseña.setBackground(new java.awt.Color(255, 0, 0));
        txtContraseña.setBounds(230, 430, 180, 30);
        jLayeredPane1.add(txtContraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtRepitaContraseña.setBackground(new java.awt.Color(255, 0, 0));
        txtRepitaContraseña.setBounds(230, 470, 180, 30);
        jLayeredPane1.add(txtRepitaContraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtSegundoApellido.setBackground(new java.awt.Color(255, 0, 0));
        txtSegundoApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSegundoApellido.setBounds(220, 130, 170, 30);
        jLayeredPane1.add(txtSegundoApellido, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SEGUNDO APELLIDO");
        jLabel9.setBounds(30, 130, 130, 20);
        jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SEGUNDO NOMBRE");
        jLabel10.setBounds(30, 60, 150, 20);
        jLayeredPane1.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtSegundoNombre.setBackground(new java.awt.Color(255, 0, 0));
        txtSegundoNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSegundoNombre.setBounds(220, 50, 170, 30);
        jLayeredPane1.add(txtSegundoNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOMBRE DE USUARIO");
        jLabel6.setBounds(30, 400, 170, 15);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup2.add(rSi);
        rSi.setText("SI");
        rSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSiActionPerformed(evt);
            }
        });
        rSi.setBounds(420, 60, 40, 23);
        jLayeredPane1.add(rSi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup2.add(rNo);
        rNo.setSelected(true);
        rNo.setText("NO");
        rNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNoActionPerformed(evt);
            }
        });
        rNo.setBounds(470, 60, 40, 23);
        jLayeredPane1.add(rNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup3.add(rS);
        rS.setText("SI");
        rS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSActionPerformed(evt);
            }
        });
        rS.setBounds(420, 130, 40, 23);
        jLayeredPane1.add(rS, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup3.add(rN);
        rN.setSelected(true);
        rN.setText("NO");
        rN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNActionPerformed(evt);
            }
        });
        rN.setBounds(480, 130, 50, 23);
        jLayeredPane1.add(rN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "EL CAMPO NOMBRE DEBE ESTAR LLENO" + txtNombre.getText(), "NOMBRE", JOptionPane.ERROR_MESSAGE);
        }

        if (txtSegundoNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "EL CAMPO SEGUNDO NOMBRE DEBE ESTAR LLENO" + txtSegundoNombre.getText(), "NOMBRE", JOptionPane.ERROR_MESSAGE);
        }
        if (txtApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "EL CAMPO APELLIDO DEBE ESTAR LLENO" + txtApellido.getText(), "APELLIDO", JOptionPane.ERROR_MESSAGE);
        }

        if (txtSegundoApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "EL CAMPO SEGUNDO APELLIDO DEBE ESTAR LLENO" + txtSegundoApellido.getText(), "APELLIDO", JOptionPane.ERROR_MESSAGE);
        }
        if (txtContraseña.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "EL CAMPO CONTRASEÑA DEBE ESTAR LLENO" + txtContraseña.getText(), "CONTRASEÑA", JOptionPane.ERROR_MESSAGE);
        }

        if (txtRepitaContraseña.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "EL CAMPO CONTRASEÑA DEBE ESTAR LLENO" + txtRepitaContraseña.getText(), "CONTRASEÑA", JOptionPane.ERROR_MESSAGE);

            InterfazBienvenida a = new InterfazBienvenida();
            a.setVisible(true);
            setVisible(false);

        }
        
        if (txtNombre.getText().length() > 0 && txtSegundoNombre.getText().length() > 0 && txtApellido.getText().length() > 0 && txtSegundoApellido.getText().length() > 0 && txtContraseña.getText().length() > 0 && txtRepitaContraseña.getText().length() > 0) {
            String primerLetra, segundaLetra, apellido, segApellido, nombreDeUsuario, fecha;
            String primera, segunda, inicialApellido, inicialSegundoApellido, date;
            primerLetra = txtNombre.getText().substring(0, 2);
            segundaLetra = txtSegundoNombre.getText().substring(0, 2);
            apellido = txtApellido.getText().substring(0, 2);
            segApellido = txtSegundoApellido.getText().substring(0, 2);
            fecha = cbAño.getSelectedItem().toString().substring(2, 4);
            primera = primerLetra;
            segunda = segundaLetra;
            inicialApellido = apellido;
            inicialSegundoApellido = segApellido;
            date = fecha;

            nombreDeUsuario = primera + segunda + inicialApellido + inicialSegundoApellido + fecha;

            txtNombreUsuario.setText(String.valueOf(nombreDeUsuario));

        }
        String contra1;
        if (txtContraseña.getText().length() > 0) {
            contra1 = txtContraseña.getText();
            String contra2;
            contra2 = txtRepitaContraseña.getText();
            if (contra1.equals(contra2)) {

                JOptionPane.showMessageDialog(this, "CONTRASEÑA CORRECTA", "VALIDACION", JOptionPane.INFORMATION_MESSAGE);
            }
        }
           
        if (txtNombre.getText().length() > 0 && txtSegundoNombre.getText().length() > 0 && txtApellido.getText().length() > 0 && txtSegundoApellido.getText().length() > 0 && txtContraseña.getText().length() > 0 && txtRepitaContraseña.getText().length() > 0) {
            conectar cc = new conectar();
            Connection cn = cc.conexion();
            String primerNombre, segundoNombre, primerApellido, segundoApellido, nombreUsuario, contrasenna;
            String sql = "";

            primerNombre = txtNombre.getText();
            segundoNombre = txtSegundoNombre.getText();
            primerApellido = txtApellido.getText();
            segundoApellido = txtSegundoApellido.getText();
            nombreUsuario = txtNombreUsuario.getText();
            contrasenna = txtContraseña.getText();
            sql = "INSERT INTO registro (primerNombre, segundoNombre, primerApellido, segundoApellido,nombreUsuario,contrasenna) VALUES (?,?,?,?,?,?)";

            try {
                PreparedStatement pst = cn.prepareStatement(sql);
                pst.setString(1, primerNombre);
                pst.setString(2, segundoNombre);
                pst.setString(3, primerApellido);
                pst.setString(4, segundoApellido);
                pst.setString(5, nombreUsuario);
                pst.setString(6, contrasenna);
                int a = pst.executeUpdate();
                if (a > 0) {
                    JOptionPane.showMessageDialog(this, "USUARIO REGISTRADO SU NOMBRE DE USUARIO ES " + txtNombreUsuario.getText(), "BIENVENIDO", JOptionPane.INFORMATION_MESSAGE);

                    InterfazIniciarSecion b = new InterfazIniciarSecion();
                    b.setVisible(true);
                    setVisible(false);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "USUARIO YA ESTA REGISTRADO", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        if (!txtNombre.getText().matches("[/s a-zA-z]*")) {
            JOptionPane.showMessageDialog(this, "EL CAMPO NOMBRE SOLO RECIBE CARACTERES ALFABETICOS", "VALIDACION", JOptionPane.INFORMATION_MESSAGE);
            txtNombre.setText("");
        }
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyReleased
        if (!txtApellido.getText().matches("[/s a-zA-z]*")) {
            JOptionPane.showMessageDialog(this, "EL CAMPO APELLIDO SOLO RECIBE CARACTERES ALFABETICOS", "VALIDACION", JOptionPane.INFORMATION_MESSAGE);
            txtApellido.setText("");
        }
    }//GEN-LAST:event_txtApellidoKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        InterfazBienvenida a = new InterfazBienvenida();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSiActionPerformed
        if (rSi.isSelected()) {
            txtSegundoNombre.setEnabled(true);
            txtSegundoNombre.setText("");
        }
    }//GEN-LAST:event_rSiActionPerformed

    private void rNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNoActionPerformed
        if (rNo.isSelected()) {
            txtSegundoNombre.setEnabled(false);
            txtSegundoNombre.setText("xx");
        }
    }//GEN-LAST:event_rNoActionPerformed

    private void rNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNActionPerformed
        if (rN.isSelected()) {
            txtSegundoApellido.setEnabled(false);
            txtSegundoApellido.setText("xx");
        }
    }//GEN-LAST:event_rNActionPerformed

    private void rSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSActionPerformed
        if (rS.isSelected()) {
            txtSegundoApellido.setEnabled(true);
            txtSegundoApellido.setText("");
        }
    }//GEN-LAST:event_rSActionPerformed

    private void cbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPaisActionPerformed

    private void cbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InterfazLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox cbAño;
    private javax.swing.JComboBox cbDia;
    private javax.swing.JComboBox cbMes;
    private javax.swing.JComboBox cbPais;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JRadioButton rN;
    private javax.swing.JRadioButton rNo;
    private javax.swing.JRadioButton rS;
    private javax.swing.JRadioButton rSi;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtRepitaContraseña;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtSegundoNombre;
    // End of variables declaration//GEN-END:variables

    private void llenarCombo() {
        cbMes.addItem("ENERO");
        cbMes.addItem("FEBRERO");
        cbMes.addItem("MARZO");
        cbMes.addItem("ABRIL");
        cbMes.addItem("MAYO");
        cbMes.addItem("JUNIO");
        cbMes.addItem("JULIO");
        cbMes.addItem("AGOSTO");
        cbMes.addItem("SEPTIEMBRE");
        cbMes.addItem("OCTUBRE");
        cbMes.addItem("NOVIEMBRE");
        cbMes.addItem("DICIEMBRE");
    }

    private void llenarComboPais() {
        cbPais.addItem("ARGENTINA");
        cbPais.addItem("BOLIVIA");
        cbPais.addItem("COLOMBIA");
        cbPais.addItem("BRAZIL");
        cbPais.addItem("CHILE");
        cbPais.addItem("VENEZUELA");
        cbPais.addItem("ECUADOR");
        cbPais.addItem("PARAGUAY");
        cbPais.addItem("URUGUAY");
        cbPais.addItem("PERU");

    }
}
